name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: "dev"

      action:
        description: "Terraform Action"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply

permissions:
  id-token: write
  contents: read

jobs:

  terraform:

    environment:
      name: dev

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::664418996643:role/github-actions-terraform-role
          aws-region: us-east-1

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Debug Repository
        run: |
          pwd
          ls -R

      - name: Package Lambda
        run: |
          mkdir -p build
          cd scripts
          zip -r ../build/lambda.zip .

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        if: github.event.inputs.action == 'plan'
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        working-directory: terraform
        run: terraform apply -auto-approve